# Generated by Django 6.0.7 on 2026-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('driver', 'Driver application'), ('ride', 'Ride request (family / school)'), ('contact', 'General contact')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Form-specific fields (vehicle, school, schedule...)')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website inquiry',
                'verbose_name_plural': 'Website inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
