# Generated by Django 6.0.7 on 2026-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Emergency contact name'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Emergency contact phone'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=60, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance expiry'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Insurance provider'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='License expiry'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='License number'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'Washington DC')], default='TX', max_length=2, verbose_name='License state'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'Washington DC')], default='TX', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=40, verbose_name='Vehicle color'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=60, verbose_name='Vehicle make'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=60, verbose_name='Vehicle model'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vehicle year'),
        ),
    ]
