# Generated by Django 6.0.7 on 2026-10-11 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_i18n_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='applicant_message',
            field=models.TextField(blank=True, verbose_name='Message from applicant'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=5, verbose_name='Preferred language'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Vehicle type'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('in_progress', 'In progress'), ('submitted', 'Under review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Not approved'), ('inactive', 'Inactive')], db_index=True, default='interested', max_length=20),
        ),
    ]
